### ISSUE TITLE
Code math

### ISSUE THREAD

**Issue by sochio16** [sochio16/Bacis_C#15]
Please make function of sum a and b.

**Comment by ChhailengTim** [comment]
#include <stdio.h>
int Add(int a,int b){
    int sum;
    sum=a+b;
    return (sum);
}
int main() {
     int a, b, res;
 
   printf("\nEnter the a numbers : ");
   scanf("%d", &a);
   printf("\nEnter the b numbers : ");
   scanf("%d", &b);
 
   //Call Function Sum With Two Parameters
   res = Add(a, b);
   printf("Addition of two number is : %d",res);
} #

**Comment by ChhailengTim** [comment]
is it done?
